name: Build_Latest

on: [push]

env:
  DEST_NAME: auto_release

jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
     
    - name: Restore NuGet Packages
      run: nuget restore N_m3u8DL-CLI.sln
 
    - name: Build app for release
      run: msbuild N_m3u8DL-CLI.sln /p:Configuration=Release /p:DebugSymbols=false /p:DebugType=None

    - name: Upload Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: N_m3u8DL-CLI_latest
        path: N_m3u8DL-CLI\bin\Release\N_m3u8DL-CLI.exe

    - name: Package
      run: Compress-Archive -Path N_m3u8DL-CLI\bin\* -Destination ${{env.DEST_NAME}}.zip

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        tag_name: ${{env.DEST_NAME}}
        name: Release ${{ github.sha }}
        body: 由提交${{ github.sha }}自动触发编译生成的Release。
        draft: false
        prerelease: false
        files: |
          ${{env.DEST_NAME}}.zip
